`include "FullAdder.v"
`include "GPTree.v"

module Adder32 (
    input   wire[31:0]   a,
    input   wire[31:0]   b,
    input   wire    c_in,
    output  wire[31:0]   s,
    output  wire    c_out
);

    wire [31:0] G;
    wire [31:0] P;
    wire [31:0] co; // generated by Han-Carlson tree
    wire [31:0] ci;
    assign {c_out, ci} = {co, c_in};

    genvar i;
    generate
        for (i = 0; i <= 31; i = i + 1) begin: adder_gen
            FullAdder adder(
                .a  (a[i]),
                .b  (b[i]),
                .ci (ci[i]),
                .s  (s[i]),
                .G  (G[i]),
                .P  (P[i])
            );
        end
    endgenerate

    GPTree hc_tree(G, P, c_in, co);

endmodule